# Generated by Django 3.2.3 on 2021-05-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=120)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=50)),
                ('mileage', models.CharField(max_length=50)),
            ],
        ),
    ]
